# Linker config for fast compiles
# Using the default MSVC linker - rust-lld requires cargo-binutils setup.
# If you install cargo-binutils, uncomment below for faster linking:
# [target.x86_64-pc-windows-msvc]
# linker = "rust-lld.exe"
